// <auto-generated />
using System;
using E_Tickets.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace E_Tickets.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241017012406_one")]
    partial class one
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("E_Tickets.Models.Actor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("News")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePictrue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Actors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "Ryan Reynolds is a Canadian actor and producer best known for his roles in films such as Deadpool, The Proposal, and Free Guy. He has established himself as one of the most charismatic and humorous actors in Hollywood.",
                            FirstName = "Ryan",
                            LastName = "Reynolds",
                            News = "Reynolds is currently filming the highly anticipated Deadpool 3, where he will reprise his iconic role alongside Hugh Jackman as Wolverine.",
                            ProfilePictrue = "Ryan Reynolds.jpg"
                        },
                        new
                        {
                            Id = 2,
                            Bio = "Hugh Jackman is an Australian actor, singer, and producer. He is best known for his role as Wolverine in the X-Men series and his performances in Les Misérables and The Greatest Showman.",
                            FirstName = "Hugh",
                            LastName = "Jackman",
                            News = "Jackman is set to return as Wolverine in Deadpool 3, marking his return to the role after his supposed final appearance in 2017's Logan.",
                            ProfilePictrue = "Hugh Jackman.jpg"
                        },
                        new
                        {
                            Id = 3,
                            Bio = "Joaquin Phoenix is an American actor known for his intense and unconventional performances. He won an Academy Award for his role as Arthur Fleck in Joker and has appeared in films like Gladiator and Her.",
                            FirstName = "Joaquin",
                            LastName = "Phoenix",
                            News = "Phoenix is set to return as Arthur Fleck in Joker: Folie à Deux, the much-anticipated sequel to his award-winning performance.",
                            ProfilePictrue = "Joaquin Phoenix.jpg"
                        },
                        new
                        {
                            Id = 4,
                            Bio = "Zendaya is an American actress and singer who rose to fame with her role in the Disney Channel series Shake It Up and has since become known for her performances in Euphoria and Dune.",
                            FirstName = "Zendaya",
                            LastName = "",
                            News = "Zendaya will reprise her role as Chani in Dune: Part Two, continuing the sci-fi epic alongside Timothée Chalamet.",
                            ProfilePictrue = "Zendaya.jpg"
                        },
                        new
                        {
                            Id = 5,
                            Bio = "Margot Robbie is an Australian actress and producer known for her roles in films such as The Wolf of Wall Street, Suicide Squad, and Barbie. She has earned widespread acclaim for her versatility and charm.",
                            FirstName = "Margot",
                            LastName = "Robbie",
                            News = "Robbie is rumored to appear in a future installment of the DC Universe, continuing her portrayal of Harley Quinn.",
                            ProfilePictrue = "Margot Robbie.jpg"
                        },
                        new
                        {
                            Id = 6,
                            Bio = "Timothée Chalamet is an American actor who gained recognition for his performances in films such as Call Me by Your Name, Lady Bird, and Dune. He is known for his intense and emotional acting style.",
                            FirstName = "Timothée",
                            LastName = "Chalamet",
                            News = "Chalamet will reprise his role as Paul Atreides in Dune: Part Two, continuing the epic saga of Frank Herbert's novel.",
                            ProfilePictrue = "Timothée Chalamet.jpg"
                        },
                        new
                        {
                            Id = 7,
                            Bio = "Florence Pugh is a British actress known for her powerful performances in films such as Midsommar, Little Women, and Don't Worry Darling. She has quickly become one of Hollywood's most respected young talents.",
                            FirstName = "Florence",
                            LastName = "Pugh",
                            News = "Pugh is set to star in Dune: Part Two as Princess Irulan, marking her entry into the science fiction genre.",
                            ProfilePictrue = "Florence Pugh.jpg"
                        },
                        new
                        {
                            Id = 8,
                            Bio = "Tom Hardy is an English actor and producer known for his versatile roles in both film and television. He has received critical acclaim for his performances in movies like Mad Max: Fury Road, The Revenant, and Venom. Hardy is also known for his roles in popular films such as Inception and Dunkirk.",
                            FirstName = "Tom",
                            LastName = "Hardy",
                            News = "Hardy is set to reprise his role as Eddie Brock in the upcoming Venom sequel, Venom: The Last Dance.",
                            ProfilePictrue = "Tom Hardy.jpg"
                        },
                        new
                        {
                            Id = 9,
                            Bio = "Daniel Kaluuya is a British actor and writer known for his roles in Get Out, Black Panther, and Judas and the Black Messiah. He won an Academy Award for Best Supporting Actor for his portrayal of Fred Hampton.",
                            FirstName = "Daniel",
                            LastName = "Kaluuya",
                            News = "Kaluuya will star in the upcoming Marvel film, set to expand his presence in the superhero genre.",
                            ProfilePictrue = "Daniel Kaluuya.jpg"
                        },
                        new
                        {
                            Id = 10,
                            Bio = "Emily Blunt is a British-American actress known for her roles in films such as A Quiet Place, Mary Poppins Returns, and Edge of Tomorrow. She has received acclaim for her versatility and strong screen presence.",
                            FirstName = "Emily",
                            LastName = "Blunt",
                            News = "Blunt is set to star in the upcoming film Oppenheimer, directed by Christopher Nolan, which chronicles the life of J. Robert Oppenheimer.",
                            ProfilePictrue = "Emily Blunt.jpg"
                        },
                        new
                        {
                            Id = 11,
                            Bio = "Christian Bale is a British-American actor known for his versatility and commitment to his roles. He has received numerous accolades, including two Academy Awards. Some of his notable films include American Psycho, The Dark Knight Trilogy, and Ford v Ferrari.",
                            FirstName = "Christian",
                            LastName = "Bale",
                            News = "Bale is set to star in the upcoming film Oppenheimer, directed by Christopher Nolan, where he will portray J. Robert Oppenheimer.",
                            ProfilePictrue = "Christian Bale.jpg"
                        },
                        new
                        {
                            Id = 12,
                            Bio = "Rachel Zegler is an American actress and singer who gained fame for her role as Maria in the 2021 film adaptation of West Side Story, directed by Steven Spielberg. She is known for her powerful voice and compelling performances.",
                            FirstName = "Rachel",
                            LastName = "Zegler",
                            News = "Zegler will star as Snow White in the upcoming live-action adaptation of Disney's classic animated film.",
                            ProfilePictrue = "Rachel Zegler.jpg"
                        },
                        new
                        {
                            Id = 13,
                            Bio = "Leonardo DiCaprio is an American actor and producer known for his diverse roles in both independent films and major blockbusters. He has received numerous accolades, including an Academy Award for Best Actor for his performance in The Revenant. His notable films include Titanic, Inception, The Wolf of Wall Street, and Once Upon a Time in Hollywood.",
                            FirstName = "Leonardo",
                            LastName = "DiCaprio",
                            News = "DiCaprio is set to star in Martin Scorsese's upcoming film Killers of the Flower Moon, which tells the story of the Osage murders in the 1920s.",
                            ProfilePictrue = "Leonardo DiCaprio.jpg"
                        },
                        new
                        {
                            Id = 14,
                            Bio = "Denzel Washington is an American actor, producer, and director known for his powerful performances in both drama and action films. He has received numerous awards, including two Academy Awards for Best Actor for his roles in Training Day and Glory. Some of his notable films include Malcolm X, The Equalizer series, and Fences.",
                            FirstName = "Denzel",
                            LastName = "Washington",
                            News = "Washington is set to star in the upcoming film The Equalizer 3, continuing his role as Robert McCall.",
                            ProfilePictrue = "Denzel Washington.jpg"
                        },
                        new
                        {
                            Id = 15,
                            Bio = "Zoe Saldana is an American actress and dancer known for her roles in blockbuster franchises including Avatar, Guardians of the Galaxy, and Star Trek. She is recognized for her strong performances and has become one of the highest-grossing actresses in Hollywood.",
                            FirstName = "Zoe",
                            LastName = "Saldana",
                            News = "Saldana will reprise her role as Neytiri in the upcoming Avatar sequels, continuing her journey in James Cameron's epic sci-fi universe.",
                            ProfilePictrue = "Zoe Saldana.jpg"
                        },
                        new
                        {
                            Id = 16,
                            Bio = "Matthew McConaughey is an American actor and producer known for his charismatic performances and distinct voice. He gained fame with films such as Dazed and Confused, The Lincoln Lawyer, and Magic Mike, but he earned critical acclaim and an Academy Award for Best Actor for his role in Dallas Buyers Club.",
                            FirstName = "Matthew",
                            LastName = "McConaughey",
                            News = "McConaughey is set to star in the upcoming film The Gentleman, directed by Guy Ritchie, which follows a British drug lord and his attempts to sell off his empire.",
                            ProfilePictrue = "Matthew McConaughey.jpg"
                        });
                });

            modelBuilder.Entity("E_Tickets.Models.ActorMovie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActorId")
                        .HasColumnType("int");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.HasIndex("MovieId");

                    b.ToTable("ActorMovies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActorId = 5,
                            MovieId = 10
                        },
                        new
                        {
                            Id = 2,
                            ActorId = 6,
                            MovieId = 13
                        },
                        new
                        {
                            Id = 3,
                            ActorId = 4,
                            MovieId = 13
                        },
                        new
                        {
                            Id = 4,
                            ActorId = 9,
                            MovieId = 11
                        },
                        new
                        {
                            Id = 5,
                            ActorId = 13,
                            MovieId = 10
                        },
                        new
                        {
                            Id = 6,
                            ActorId = 10,
                            MovieId = 9
                        },
                        new
                        {
                            Id = 7,
                            ActorId = 14,
                            MovieId = 2
                        },
                        new
                        {
                            Id = 8,
                            ActorId = 15,
                            MovieId = 14
                        },
                        new
                        {
                            Id = 9,
                            ActorId = 3,
                            MovieId = 6
                        },
                        new
                        {
                            Id = 10,
                            ActorId = 13,
                            MovieId = 4
                        },
                        new
                        {
                            Id = 11,
                            ActorId = 1,
                            MovieId = 7
                        },
                        new
                        {
                            Id = 12,
                            ActorId = 2,
                            MovieId = 7
                        },
                        new
                        {
                            Id = 13,
                            ActorId = 8,
                            MovieId = 3
                        },
                        new
                        {
                            Id = 14,
                            ActorId = 16,
                            MovieId = 5
                        },
                        new
                        {
                            Id = 15,
                            ActorId = 2,
                            MovieId = 8
                        },
                        new
                        {
                            Id = 16,
                            ActorId = 11,
                            MovieId = 8
                        },
                        new
                        {
                            Id = 17,
                            ActorId = 11,
                            MovieId = 1
                        },
                        new
                        {
                            Id = 18,
                            ActorId = 12,
                            MovieId = 12
                        },
                        new
                        {
                            Id = 19,
                            ActorId = 7,
                            MovieId = 13
                        });
                });

            modelBuilder.Entity("E_Tickets.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Comedy"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Drama"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Sci-Fi"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Cartoon"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Horror"
                        });
                });

            modelBuilder.Entity("E_Tickets.Models.Cinema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CinemaLogo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cinemas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = " Mall of Egypt Cinema",
                            CinemaLogo = "Vox.jpg",
                            Description = "Step into a world where stories come to life at VOX Cinema, a state-of-the-art movie theater designed to provide the ultimate cinematic experience. this modern theater features plush, reclining seats and crystal-clear surround sound that immerses you in every moment. Whether you're here for the latest blockbuster, an indie gem, or a family-friendly flick, our giant screens deliver stunning visuals, transporting you to new worlds. Enjoy a wide selection of snacks, from classic buttered popcorn to gourmet treats, and make the most of our comfortable, spacious seating. With a range of movie times and special screenings, [Theater Name] offers something for every movie lover. Whether it's a solo escape, a night out with friends, or a family outing, your perfect movie experience starts here.",
                            Name = "VOX"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Nasr City",
                            CinemaLogo = "City Stars.jpg",
                            Description = "Step into a world where stories come to life at City Stars Cinema, a state-of-the-art movie theater designed to provide the ultimate cinematic experience. this modern theater features plush, reclining seats and crystal-clear surround sound that immerses you in every moment. Whether you're here for the latest blockbuster, an indie gem, or a family-friendly flick, our giant screens deliver stunning visuals, transporting you to new worlds. Enjoy a wide selection of snacks, from classic buttered popcorn to gourmet treats, and make the most of our comfortable, spacious seating. With a range of movie times and special screenings, [Theater Name] offers something for every movie lover. Whether it's a solo escape, a night out with friends, or a family outing, your perfect movie experience starts here.",
                            Name = "City Stars "
                        },
                        new
                        {
                            Id = 3,
                            Address = "The 5Th Settlement",
                            CinemaLogo = "Point 90.jpg",
                            Description = "Step into a world where stories come to life at Point 90 Cinema, a state-of-the-art movie theater designed to provide the ultimate cinematic experience. this modern theater features plush, reclining seats and crystal-clear surround sound that immerses you in every moment. Whether you're here for the latest blockbuster, an indie gem, or a family-friendly flick, our giant screens deliver stunning visuals, transporting you to new worlds. Enjoy a wide selection of snacks, from classic buttered popcorn to gourmet treats, and make the most of our comfortable, spacious seating. With a range of movie times and special screenings, [Theater Name] offers something for every movie lover. Whether it's a solo escape, a night out with friends, or a family outing, your perfect movie experience starts here.",
                            Name = "Point 90 "
                        },
                        new
                        {
                            Id = 4,
                            Address = "Sheikh Zayed City",
                            CinemaLogo = "Americana IMAX.jpg",
                            Description = "Step into a world where stories come to life at Americana IMAX Cinema, a state-of-the-art movie theater designed to provide the ultimate cinematic experience. this modern theater features plush, reclining seats and crystal-clear surround sound that immerses you in every moment. Whether you're here for the latest blockbuster, an indie gem, or a family-friendly flick, our giant screens deliver stunning visuals, transporting you to new worlds. Enjoy a wide selection of snacks, from classic buttered popcorn to gourmet treats, and make the most of our comfortable, spacious seating. With a range of movie times and special screenings, [Theater Name] offers something for every movie lover. Whether it's a solo escape, a night out with friends, or a family outing, your perfect movie experience starts here.",
                            Name = "Americana IMAX "
                        },
                        new
                        {
                            Id = 5,
                            Address = "DownTown",
                            CinemaLogo = "Zawya.jpg",
                            Description = "Step into a world where stories come to life at Zawya Cinema, a state-of-the-art movie theater designed to provide the ultimate cinematic experience. this modern theater features plush, reclining seats and crystal-clear surround sound that immerses you in every moment. Whether you're here for the latest blockbuster, an indie gem, or a family-friendly flick, our giant screens deliver stunning visuals, transporting you to new worlds. Enjoy a wide selection of snacks, from classic buttered popcorn to gourmet treats, and make the most of our comfortable, spacious seating. With a range of movie times and special screenings, [Theater Name] offers something for every movie lover. Whether it's a solo escape, a night out with friends, or a family outing, your perfect movie experience starts here.",
                            Name = "Zawya "
                        },
                        new
                        {
                            Id = 6,
                            Address = "ElMaadi ",
                            CinemaLogo = "Galaxy.jpg",
                            Description = "Step into a world where stories come to life at Galaxy Cinema, a state-of-the-art movie theater designed to provide the ultimate cinematic experience. this modern theater features plush, reclining seats and crystal-clear surround sound that immerses you in every moment. Whether you're here for the latest blockbuster, an indie gem, or a family-friendly flick, our giant screens deliver stunning visuals, transporting you to new worlds. Enjoy a wide selection of snacks, from classic buttered popcorn to gourmet treats, and make the most of our comfortable, spacious seating. With a range of movie times and special screenings, [Theater Name] offers something for every movie lover. Whether it's a solo escape, a night out with friends, or a family outing, your perfect movie experience starts here.",
                            Name = "Galaxy  "
                        },
                        new
                        {
                            Id = 7,
                            Address = " Behind Masaken Sheraton",
                            CinemaLogo = "SunCity.PNg",
                            Description = "Step into a world where stories come to life at Sun City Cinema, a state-of-the-art movie theater designed to provide the ultimate cinematic experience. this modern theater features plush, reclining seats and crystal-clear surround sound that immerses you in every moment. Whether you're here for the latest blockbuster, an indie gem, or a family-friendly flick, our giant screens deliver stunning visuals, transporting you to new worlds. Enjoy a wide selection of snacks, from classic buttered popcorn to gourmet treats, and make the most of our comfortable, spacious seating. With a range of movie times and special screenings, [Theater Name] offers something for every movie lover. Whether it's a solo escape, a night out with friends, or a family outing, your perfect movie experience starts here.",
                            Name = "Sun City "
                        });
                });

            modelBuilder.Entity("E_Tickets.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("CinemaId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MovieStatus")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrailerUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CinemaId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CinemaId = 1,
                            Description = "When the menace known as the Joker emerges from his mysterious past, he wreaks havoc and chaos on the people of Gotham. The Dark Knight must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
                            EndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(1965),
                            ImgUrl = "The Dark Knight.jpg",
                            MovieStatus = 2,
                            Name = "The Dark Knight",
                            Price = "12.99",
                            StartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(1983),
                            TrailerUrl = "EXeTwQWrcwY"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            CinemaId = 2,
                            Description = "A faded television actor and his stunt double strive to achieve fame and success in the film industry during the final years of Hollywood's Golden Age in 1969 Los Angeles.",
                            EndDate = new DateTime(2024, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImgUrl = "Once Upon a Time... in Hollywood.jpg",
                            MovieStatus = 2,
                            Name = "Once Upon a Time... in Hollywood",
                            Price = "12.99",
                            StartDate = new DateTime(2019, 7, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrailerUrl = "ELeMaP8EPAA"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CinemaId = 3,
                            Description = "Eddie Brock struggles to adapt to his new life as the host of Venom, while facing off against new threats that challenge his dual existence. As he delves deeper into the world of anti-heroes, he must confront his own inner demons.",
                            EndDate = new DateTime(2024, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImgUrl = "Venom The Last Dance.jpg",
                            MovieStatus = 0,
                            Name = "Venom: The Last Dance",
                            Price = "12.99",
                            StartDate = new DateTime(2024, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrailerUrl = "HyIyd9joTTc"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 3,
                            CinemaId = 4,
                            Description = "Based on true events, this film follows the investigation into a series of murders targeting wealthy Osage people in 1920s Oklahoma, sparking the birth of the FBI.",
                            EndDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImgUrl = "Killers of the Flower Moon.jpg",
                            MovieStatus = 1,
                            Name = "Killers of the Flower Moon",
                            Price = "14.99",
                            StartDate = new DateTime(2023, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrailerUrl = "EP34Yoxs3FQ"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 4,
                            CinemaId = 5,
                            Description = "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
                            EndDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(1979),
                            ImgUrl = "Interstellar.jpg",
                            MovieStatus = 2,
                            Name = "Interstellar",
                            Price = "13.99",
                            StartDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(1996),
                            TrailerUrl = "zSWdZVtXT7E"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            CinemaId = 6,
                            Description = "Sequel to the 2019 film Joker, following Arthur Fleck as he continues to descend into madness, with new characters joining his dark world.",
                            EndDate = new DateTime(2025, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImgUrl = "Joker Folie à Deux.jpg",
                            MovieStatus = 0,
                            Name = "Joker: Folie à Deux",
                            Price = "16.99",
                            StartDate = new DateTime(2024, 10, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrailerUrl = "_OKAwz2MsJs"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            CinemaId = 7,
                            Description = "The merc with a mouth, Deadpool, teams up with Wolverine in a chaotic adventure that crosses timelines and dimensions. Expect a mix of humor, action, and the unexpected in this highly anticipated sequel.",
                            EndDate = new DateTime(2024, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImgUrl = "Deadpool & Wolverine.jpg",
                            MovieStatus = 0,
                            Name = "Deadpool & Wolverine",
                            Price = "17.99",
                            StartDate = new DateTime(2024, 7, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrailerUrl = "73_1biulkYk"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            CinemaId = 1,
                            Description = "In late 19th century London, two rival magicians, Robert Angier and Alfred Borden, compete to create the ultimate stage illusion while sacrificing everything they have to outwit each other. Their obsession leads to tragic consequences as they delve into the world of magic and deception.",
                            EndDate = new DateTime(2024, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImgUrl = "The Prestige.jpg",
                            MovieStatus = 2,
                            Name = "The Prestige",
                            Price = "9.99",
                            StartDate = new DateTime(2006, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrailerUrl = "ELq7V8vkekI"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            CinemaId = 2,
                            Description = "In a future where Earth is invaded by aliens, a public relations officer finds himself caught in a time loop, reliving the same day over and over again. With the help of a skilled warrior, he learns how to fight back and save humanity.",
                            EndDate = new DateTime(2024, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImgUrl = "Edge of Tomorrow.jpg",
                            MovieStatus = 2,
                            Name = "Edge of Tomorrow",
                            Price = "9.99",
                            StartDate = new DateTime(2014, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrailerUrl = "yUmSVcttXnI"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CinemaId = 3,
                            Description = "Robert McCall finds himself at home in Southern Italy, but he discovers his friends are under the control of local crime bosses. As events turn deadly, McCall knows what he has to do: become his friends' protector by taking on the mafia.",
                            EndDate = new DateTime(2024, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImgUrl = "The Equalizer 3.jpg",
                            MovieStatus = 1,
                            Name = "The Equalizer 3",
                            Price = "15.99",
                            StartDate = new DateTime(2023, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrailerUrl = "19ikl8vy4zs"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 5,
                            CinemaId = 4,
                            Description = "Miles Morales returns for the next chapter of the Oscar-winning animated saga. He meets Gwen Stacy and teams up with a new group of Spider-People to face a powerful villain while navigating the multiverse.",
                            EndDate = new DateTime(2024, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImgUrl = "Across the Spider-Verse.jpg",
                            MovieStatus = 1,
                            Name = "Spider-Man: Across the Spider-Verse",
                            Price = "14.99",
                            StartDate = new DateTime(2023, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrailerUrl = "cqGjhVJWtEg"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 1,
                            CinemaId = 5,
                            Description = "This prequel to The Hunger Games follows a young Coriolanus Snow as he mentors the District 12 tribute in the 10th Hunger Games, setting the stage for his rise to power.",
                            EndDate = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImgUrl = "The Hunger Games The Ballad of Songbirds & Snakes.jpg",
                            MovieStatus = 0,
                            Name = "The Ballad of Songbirds and Snakes",
                            Price = "15.99",
                            StartDate = new DateTime(2023, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrailerUrl = "NxW_X4kzeus"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 1,
                            CinemaId = 6,
                            Description = "Paul Atreides unites with Chani and the Fremen while seeking revenge against those who destroyed his family. He must face a choice between the love of his life and the fate of the universe.",
                            EndDate = new DateTime(2024, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImgUrl = "Dune Part Two.jpg",
                            MovieStatus = 0,
                            Name = "Dune: Part Two",
                            Price = "16.99",
                            StartDate = new DateTime(2024, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrailerUrl = "poWiludgQCw"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 4,
                            CinemaId = 7,
                            Description = "The third installment of James Cameron’s epic Avatar franchise continues the journey of the Na'vi people on Pandora, with new adventures and challenges in the breathtaking world of the planet's oceans and beyond.",
                            EndDate = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImgUrl = "Avatar 3.Png",
                            MovieStatus = 0,
                            Name = "Avatar 3",
                            Price = "19.99",
                            StartDate = new DateTime(2024, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrailerUrl = "d9MyW72ELq0"
                        });
                });

            modelBuilder.Entity("E_Tickets.Models.ActorMovie", b =>
                {
                    b.HasOne("E_Tickets.Models.Actor", "Actor")
                        .WithMany("ActorMovies")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E_Tickets.Models.Movie", "Movie")
                        .WithMany("ActorMovies")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("E_Tickets.Models.Movie", b =>
                {
                    b.HasOne("E_Tickets.Models.Category", "Category")
                        .WithMany("Movies")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("E_Tickets.Models.Cinema", "Cinema")
                        .WithMany("Movies")
                        .HasForeignKey("CinemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Cinema");
                });

            modelBuilder.Entity("E_Tickets.Models.Actor", b =>
                {
                    b.Navigation("ActorMovies");
                });

            modelBuilder.Entity("E_Tickets.Models.Category", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("E_Tickets.Models.Cinema", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("E_Tickets.Models.Movie", b =>
                {
                    b.Navigation("ActorMovies");
                });
#pragma warning restore 612, 618
        }
    }
}
